-- MySQL Script generated by MySQL Workbench
-- 07/19/15 02:15:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema phadmin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phadmin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phadmin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `phadmin` ;

-- -----------------------------------------------------
-- Table `phadmin`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`permisos` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT 'codigo del permiso',
  `descripcion` VARCHAR(125) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Es el estado de los permisos \n1---> Activo\n2---> Inactivo',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`rolPermisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`rolPermisos` (
  `codigoRol` INT NOT NULL AUTO_INCREMENT,
  `codigoPermiso` INT NOT NULL,
  PRIMARY KEY (`codigoRol`),
  INDEX `fk_rolPermisos_permisos1_idx` (`codigoPermiso` ASC),
  CONSTRAINT `fk_rolPermisos_permisos1`
    FOREIGN KEY (`codigoPermiso`)
    REFERENCES `phadmin`.`permisos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`rol` (
  `descripcionRol` VARCHAR(125) NOT NULL COMMENT 'Es la descripcion del rol',
  `estadoRol` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Es el estado del rol\n1-->Activo\n2-->Inactivo',
  `codigoRol` INT NOT NULL AUTO_INCREMENT COMMENT 'Codigo del rol',
  PRIMARY KEY (`codigoRol`),
  CONSTRAINT `fk_rol_rolPermisos`
    FOREIGN KEY (`codigoRol`)
    REFERENCES `phadmin`.`rolPermisos` (`codigoRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`usuario` (
  `clave` VARCHAR(45) NOT NULL COMMENT 'Es la clave del usuario',
  `correo` VARCHAR(45) NOT NULL COMMENT 'Correo del usuario',
  `nombres` VARCHAR(45) NOT NULL COMMENT 'Nombres del usuario',
  `apellidos` VARCHAR(45) NOT NULL COMMENT 'Apellidos del usuario',
  `direccion` VARCHAR(45) NOT NULL COMMENT 'Es la direccion del usuario',
  `numeroCelular` VARCHAR(25) NOT NULL COMMENT 'Numero de celular del usuario',
  `numeroFijo` VARCHAR(15) NULL COMMENT 'Numero de la casa o de contacto del usuario',
  `numeroDocumento` INT(30) NOT NULL COMMENT 'Numero de documento del usuario',
  `tipoDocumento` VARCHAR(10) NOT NULL COMMENT 'Tipo de documento\nCC---> Cedula\nTI--->Tarjeta de identidad\nCE-->Cedula de Extranjeria\nNIT-->Numero de id de la empresa\nPasaporte',
  `codigoRol` INT NOT NULL,
  `codigoUsuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Es el id del usuario',
  `estadoUsuario` TINYINT(1) NOT NULL DEFAULT 1,
  `fechaIngreso` DATE NOT NULL,
  `fechaSalida` DATE NOT NULL,
  PRIMARY KEY (`codigoUsuario`),
  INDEX `fk_usuario_rol1_idx` (`codigoRol` ASC),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`codigoRol`)
    REFERENCES `phadmin`.`rol` (`codigoRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`empleado` (
  `codigoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `seguro` VARCHAR(45) NOT NULL,
  `arp` VARCHAR(45) NOT NULL,
  `tipoContrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoEmpleado`),
  CONSTRAINT `fk_empleado_usuario1`
    FOREIGN KEY (`codigoEmpleado`)
    REFERENCES `phadmin`.`usuario` (`codigoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`propietario` (
  `codigoPropietario` INT NOT NULL AUTO_INCREMENT,
  `numeroContacto` INT(35) NOT NULL,
  `codigoSolicitud` INT NOT NULL,
  PRIMARY KEY (`codigoPropietario`),
  CONSTRAINT `fk_propietario_usuario1`
    FOREIGN KEY (`codigoPropietario`)
    REFERENCES `phadmin`.`usuario` (`codigoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`prooveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`prooveedor` (
  `codigoProoveedor` INT NOT NULL AUTO_INCREMENT,
  `descripcionProoveedor` VARCHAR(125) NOT NULL,
  `tipoProoveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoProoveedor`),
  CONSTRAINT `fk_prooveedor_usuario1`
    FOREIGN KEY (`codigoProoveedor`)
    REFERENCES `phadmin`.`usuario` (`codigoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`apartamento` (
  `codigoApto` INT NOT NULL AUTO_INCREMENT,
  `numeroTorre` INT(10) NOT NULL,
  `numeroApto` INT(10) NOT NULL,
  `estadoApto` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`codigoApto`),
  CONSTRAINT `fk_apartamento_propietario1`
    FOREIGN KEY (`codigoApto`)
    REFERENCES `phadmin`.`propietario` (`codigoPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`solicitud` (
  `codigoSolicitud` INT NOT NULL AUTO_INCREMENT,
  `estadoSolicitud` TINYINT(1) NOT NULL DEFAULT 1,
  `descripcionSolicitud` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`codigoSolicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`solicitudUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`solicitudUsuario` (
  `codigoPropietario` INT NOT NULL,
  `codigoSolicitud` INT NOT NULL AUTO_INCREMENT,
  `fechaSolicitud` DATETIME NOT NULL,
  `fechaRespuesta` DATETIME NOT NULL,
  PRIMARY KEY (`codigoSolicitud`),
  INDEX `fk_solicitudUsuario_propietario1_idx` (`codigoPropietario` ASC),
  CONSTRAINT `fk_solicitudUsuario_propietario1`
    FOREIGN KEY (`codigoPropietario`)
    REFERENCES `phadmin`.`propietario` (`codigoPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudUsuario_solicitud1`
    FOREIGN KEY (`codigoSolicitud`)
    REFERENCES `phadmin`.`solicitud` (`codigoSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`parqueadero` (
  `codigoParqueadero` INT NOT NULL,
  `placa` VARCHAR(15) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `ObservacionParqueadero` VARCHAR(125) NULL,
  PRIMARY KEY (`codigoParqueadero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`vehiculo` (
  `color` VARCHAR(15) NULL,
  `codigoPropietario` INT NOT NULL,
  `observacionVehiculo` VARCHAR(125) NULL,
  `placa` VARCHAR(45) NOT NULL,
  `codigoParqueadero` INT NOT NULL,
  INDEX `fk_vehiculo_propietario1_idx` (`codigoPropietario` ASC),
  PRIMARY KEY (`placa`),
  INDEX `fk_vehiculo_parqueadero1_idx` (`codigoParqueadero` ASC),
  CONSTRAINT `fk_vehiculo_propietario1`
    FOREIGN KEY (`codigoPropietario`)
    REFERENCES `phadmin`.`propietario` (`codigoPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_parqueadero1`
    FOREIGN KEY (`codigoParqueadero`)
    REFERENCES `phadmin`.`parqueadero` (`codigoParqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phadmin`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phadmin`.`publicacion` (
  `codigoPublicacion` INT NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `encabezado` VARCHAR(45) NOT NULL,
  `fechaPublicacion` DATE NOT NULL,
  `codigoEmpleado` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`codigoPublicacion`),
  INDEX `fk_publicacion_empleado1_idx` (`codigoEmpleado` ASC),
  CONSTRAINT `fk_publicacion_empleado1`
    FOREIGN KEY (`codigoEmpleado`)
    REFERENCES `phadmin`.`empleado` (`codigoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
